
description: >- # this means to ignore newlines until "baseurl:"
  So trying to write with jekyll. Not sure how this will go.


# Build settings

theme: jekyll-theme-architect
plugins:
  - jekyll-feed

